title: Juho Ylä-Jääski # your name (or website title) here
logo: "/images/face.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <ul>
  <li><a href="https://www.linkedin.com/in/juho-yl%C3%A4-j%C3%A4%C3%A4ski-191788193/"><i class="fab fa-linkedin fa-3x"></i></a></li>
  <li><a href="https://github.com/ylajaaski"><i class="fab fa-github-square fa-3x"></i></a></li>
  <li><a href="https://scholar.google.com/citations?user=2AudDOwAAAAJ&hl=en"><i class="ai ai-google-scholar-square ai-3x"></i></a></li>
  <li><a href="https://scholar.google.com/citations?user=2AudDOwAAAAJ&hl=en"><i class="ai ai-google-scholar-square ai-3x"></i><span class="link-text">Google Scholar</span></a></li>
  </ul>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
